services:
    doctrine_encrypt.orm_subscriber:
        class: DoctrineEncryptBundle\Subscribers\DoctrineEncryptSubscriber
        arguments: ["@annotation_reader", "@doctrine_encrypt.encryptor", "@debug.stopwatch"]
        tags:
            -  { name: doctrine.event_subscriber }

    doctrine_encrypt.subscriber:
        alias: doctrine_encrypt.orm_subscriber

    doctrine_encrypt.encryptor:
        class: "%doctrine_encrypt.encryptor_class_name%"
        arguments:
          - "%doctrine_encrypt.secret_key_path%"

    doctrine_encrypt.command.decrypt.database:
        class: DoctrineEncryptBundle\Command\DoctrineDecryptDatabaseCommand
        tags: ['console.command']
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@annotation_reader"
            - "doctrine_encrypt.subscriber"

    doctrine_encrypt.command.encrypt.database:
        class: DoctrineEncryptBundle\Command\DoctrineEncryptDatabaseCommand
        tags: ['console.command']
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@annotation_reader"
            - "@doctrine_encrypt.subscriber"

    doctrine_encrypt.command.encrypt.status:
        class: DoctrineEncryptBundle\Command\DoctrineEncryptStatusCommand
        tags: ['console.command']
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@annotation_reader"
            - "@doctrine_encrypt.subscriber"
